name:                polytest
version:             0.1.0.0
github:              "kerfufflev2/polytest"
license:             MIT
author:              "Kerfuffle"
copyright:           "2019 Kerfuffle"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/polytest#readme>

dependencies:
- base >= 4.7 && < 5
- polysemy >= 0.3
- random

executables:
  polytest-exe:
    main:                Main.hs
    source-dirs:         app
    default-extensions:
      - DataKinds
      - FlexibleContexts
      - GADTs
      - LambdaCase
      - PolyKinds
      - RankNTypes
      - ScopedTypeVariables
      - TypeApplications
      - TypeOperators
      - TypeFamilies
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -O2
      - -flate-specialise
      - -fspecialise-aggressively
